import type { NextPage } from 'next'
import Head from 'next/head'
import { useForm } from 'react-hook-form'
import { trpc } from '../../utils/trpc'

const CreateArtist: NextPage = () => {
  const { data, isSuccess } = trpc.useQuery(['example.getArtists'])
  const { handleSubmit, register } = useForm({
    defaultValues: {
      name: '',
    },
  })

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="p-4">
        <h1>Submit an artist below!</h1>
      </main>
      {isSuccess &&
        data.map((artist) => (
          <div key={artist.id}>
            <h2>{artist.name}</h2>
          </div>
        ))}
    </>
  )
}

export default CreateArtist
