import type { NextPage } from 'next'
import Head from 'next/head'
import { useForm } from 'react-hook-form'
import { trpc } from '../../utils/trpc'

type TechnologyCardProps = {
  name: string
  description: string
  documentation: string
}

type FormValues = {
  name: string
}

const CreateArtist: NextPage = () => {
  const { mutateAsync } = trpc.useMutation(['example.addArtist'])
  const { handleSubmit, register } = useForm({
    defaultValues: {
      name: '',
    },
  })

  const onSubmit = async (values: FormValues) => {
    try {
      console.log(values)
      const s = await mutateAsync({ name: values.name })
      console.log(s)
    } catch (err) {
      console.log(err)
    }
  }

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="p-4">
        <h1>Submit an artist below!</h1>
        <form onSubmit={handleSubmit(onSubmit)}>
          <input
            {...register('name')}
            className="block border-2 border-blue-400 p-2"
          />
          <button>Submit</button>
        </form>
      </main>
    </>
  )
}

export default CreateArtist
